name: go

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Git Project
        uses: actions/checkout@v2

      - name: Setup Go Env
        uses: actions/setup-go@v2
        with:
          go-version: '1.14.1'
        
      - name: Check Code Formatting
        run: test -z $(gofmt -l -s .) || gofmt -d -s .
        
      - name: Run Go Tests
        run: go test ./...

        
      - name: Run Code Linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.31
